### ISSUE TITLE
安装 jq 依赖失败

### ISSUE THREAD

**Issue by 0obuwawao0** [neroxps/hassio_install#1]
[info]: 切换系统网络源.....
Hit:1 http://mirrors.ustc.edu.cn/archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
[info]: 更新系统至最新.....
[info]: 安装 hassio 必要依赖.....
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package jq is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package socat
E: Package 'jq' has no installation candidate

########################### System version ###########################
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
########################### System version 2 ###########################
Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018
########################### System info ###########################
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
########################### END ###########################
\033[0;31m[ERROR]: 安装curl失败，请将检查上方安装错误信息。\033[0m
\033[0m
root@raspberrypi:/home/pi#

**Comment by neroxps** [comment]
诶，不习惯看issues~现在应该是没问题的吧？关闭问题咯
