### ISSUE TITLE
"升级脚本"部分的第一行命令写错了

### ISSUE THREAD

**Issue by jsmjsm** [neroxps/hassio_install#4]
正确应该是：`wget https://code.aliyun.com/neroxps/hassio_install/raw/master/hassio_upgrade.sh`

原文写成了`install.sh`

![8578C9E6-2166-4F7D-954E-547A54809610.png](https://i.loli.net/2020/03/15/XlpbS2svx9Ma6Ey.png)

**Comment by neroxps** [comment]
谢谢提醒，已修复。
