### ISSUE TITLE
树莓派4安装 无法从docker hub 下载hasss，是源都失效了么？

### ISSUE THREAD

**Issue by ahit976** [neroxps/hassio_install#6]
树莓派4安装时出现以下提示，10次均失败。
请问如何处理？谢谢指导！
[info]: 发现系统已安装 docker，跳过 docker 安装
[info]: 切换 Docker 源为国内源....
[info]: 切换国内源完成
[info]: 安装 hassio......
下载 hassio_install.sh 官方脚本 第1次
-=O=-                                        #     #    #     #                
从 hub.docker.com 下载 homeassistant/raspberrypi4-homeassistant:0.116.4......
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[WARNING]: 从 docker hub 下载 homeassistant/raspberrypi4-homeassistant:0.116.4 失败，第 10 次重试.
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[WARNING]: 从 docker hub 下载 homeassistant/raspberrypi4-homeassistant:0.116.4 失败，第 9 次重试.

**Comment by ahit976** [comment]
另外再请教一个问题，我的树莓派4使用wlan0上网。
在安装docker之前，ip 通过路由器dhcp获得，在路由器上绑定后是固定的。
但是，安装啦docker之后，每次启动wlan0的mac地址和ip，都会变化。
在树莓派上尝试通过改写dhcpcd.conf，则会造成wlan0失去网络连接。

**Comment by neroxps** [comment]
因为 network manage 配置的缘故,会导致 wifi 装好后断开,断开的时候脚本就失败~我没有树莓派设备,所以没法调试和修复~请使用有线来安装~
